### ISSUE TITLE
What does local rank mean in code

### ISSUE THREAD

**Issue by Humanpaladin** [lixin4ever/BERT-E2E-ABSA#13]
I don't quite understand what "local_rank" means in the code, could you explain it please? Thank you.

**Comment by lixin4ever** [comment]
Thanks for your attention.

The argument "local_rank" is used to support [DistributedDataParallel (DDP)](https://pytorch.org/docs/stable/notes/ddp.html).  

Concretely, the "local_rank" stores some local & unique information for the process, e.g., the id of the current gpu, and it can be regarded as the local identifier of each process. 

Our project is built on top of DataParallel (DP) rather than DDP, thus, you can simply leave this argument alone or adopt the default setting of this argument (i.e., set "local_rank" as -1).

**Comment by Humanpaladin** [comment]
Thank you very much for your reply.
Maybe I should learn something about the DDP later.
